import React, { useState } from 'react';
import { MdDownload } from "react-icons/md";
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

const PDFExportButton = ({ targetRef, filename, reportTitle, generatedBy }) => {
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = async () => {
    if (!targetRef.current) return;
    setIsGenerating(true);

    try {
      // 1. Capture the DOM element (Forced to pure white for print)
      const canvas = await html2canvas(targetRef.current, {
        scale: 2, 
        useCORS: true, 
        logging: false,
        backgroundColor: '#ffffff', // Pure white background for PDF
        windowWidth: 1024, 
        width: 1024       
      });

      const imgData = canvas.toDataURL('image/png');
      
      // 2. Initialize PDF (A4 size)
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      
      // 3. Layout Math (Add 15mm margins on sides)
      const margin = 15;
      const contentWidth = pdfWidth - (margin * 2);
      const imgProps = pdf.getImageProperties(imgData);
      const contentHeight = (imgProps.height * contentWidth) / imgProps.width;

      // 4. Draw Header
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(22);
      pdf.setTextColor(192, 0, 0); // UB Red
      pdf.text('UB CCSD', margin, 20);

      pdf.setFontSize(16);
      pdf.setTextColor(30, 41, 59); // Slate 800
      pdf.text(reportTitle || 'Analytics Report', margin, 30);
      
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      pdf.setTextColor(100, 116, 139); // Slate 500
      
      // ✅ Dynamic Counselor Name injection
      pdf.text(`Generated by: ${generatedBy || 'Staff'}`, margin, 38);
      pdf.text(`Date: ${new Date().toLocaleString()}`, margin, 43);

      // 5. Draw Divider Line
      pdf.setDrawColor(226, 232, 240); // Slate 200
      pdf.setLineWidth(0.5);
      pdf.line(margin, 48, pdfWidth - margin, 48);

      // 6. Inject the Dashboard Image (scaled to fit)
      const startY = 55;
      let finalHeight = contentHeight;
      
      // Prevent it from bleeding off the bottom of the page
      if (startY + contentHeight > pdfHeight - margin) {
        const scaleRatio = (pdfHeight - startY - margin) / contentHeight;
        finalHeight = contentHeight * scaleRatio;
      }

      pdf.addImage(imgData, 'PNG', margin, startY, contentWidth, finalHeight);

      // 7. Add Footer
      pdf.setFontSize(8);
      pdf.setTextColor(148, 163, 184);
      pdf.text('University of Baguio - Center for Counseling and Student Development', margin, pdfHeight - 10);

      // 8. Open in New Tab
      const pdfBlob = pdf.output('blob');
      const pdfUrl = URL.createObjectURL(pdfBlob);
      const newWindow = window.open(pdfUrl, '_blank');
      
      if (!newWindow) {
        alert("Please allow pop-ups to view the generated PDF report.");
      }

    } catch (error) {
      console.error("Failed to generate PDF", error);
      alert("An error occurred while generating the PDF.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={generatePDF}
      disabled={isGenerating}
      style={{
        display: 'flex', alignItems: 'center', gap: '8px',
        backgroundColor: isGenerating ? '#94a3b8' : '#c00000',
        color: 'white', padding: '10px 20px',
        border: 'none', fontWeight: 'bold', 
        cursor: isGenerating ? 'not-allowed' : 'pointer',
        transition: 'background-color 0.3s'
      }}
    >
      <MdDownload size={20} />
      {isGenerating ? 'Formatting...' : 'View PDF Report'}
    </button>
  );
};

export default PDFExportButton;