import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import html2canvas from 'html2canvas';
import {
  Document, Packer, Paragraph, Table, TableRow, TableCell,
  TextRun, ImageRun, HeadingLevel, WidthType,
} from 'docx';

// Capture the stats section (KPIs + charts) as a PNG
async function captureChart(el) {
  if (!el) return null;
  const canvas = await html2canvas(el, { scale: 2, backgroundColor: '#ffffff' });
  return { dataUrl: canvas.toDataURL('image/png'), w: canvas.width / 2, h: canvas.height / 2 };
}

const dataUrlToBytes = (dataUrl) => {
  const bin = atob(dataUrl.split(',')[1]);
  return Uint8Array.from(bin, (c) => c.charCodeAt(0));
};

// Build the table sections once, reuse for both formats
function buildSections({ statsData, cases }) {
  const rate = (t, c) => (t > 0 ? `${Math.round((c / t) * 100)}%` : '—');
  const isOverall = statsData.reportType === 'overall';

  const sections = [
    {
      title: 'Monthly Volume',
      headers: ['Month', 'Completed', 'Pending', 'Cancelled'],
      rows: statsData.monthlyTrend.map((m) => [m.month, m.completed, m.pending, m.declined]),
    },
    {
      title: 'Services Summary',
      headers: ['Service', 'Total', 'Completed', 'Pending', 'Cancelled', 'Completion Rate'],
      rows: statsData.servicesTable.map((s) => [
        s.service, s.total, s.completed, s.pending, s.declined, rate(s.total, s.completed),
      ]),
    },
  ];

  if (isOverall) {
    sections.push({
      title: 'Counselor Performance',
      headers: ['Counselor', 'Total', 'Completed', 'Pending', 'Cancelled', 'Completion Rate'],
      rows: statsData.counselorTable.map((c) => [
        c.name, c.total, c.completed, c.pending, c.declined, rate(c.total, c.completed),
      ]),
    });
  } else {
    sections.push({
      title: 'Weekly Breakdown',
      headers: ['Week', 'Completed', 'Pending', 'Cancelled'],
      rows: statsData.weeks.map((w) => [w.name, w.completed, w.pending, w.declined]),
    });
  }

  sections.push({
    title: isOverall ? 'Full Case Log' : 'My Case Log',
    headers: isOverall
      ? ['Date', 'Client Name', 'Service', 'Assigned To', 'Status']
      : ['Date', 'Client Name', 'Service', 'Status'],
    rows: cases.map((c) =>
      isOverall
        ? [c.date, c.client, c.service, c.assignedTo, c.status]
        : [c.date, c.client, c.service, c.status]
    ),
  });

  return sections;
}

// ── EXCEL ────────────────────────────────────────────────────────────────────
export async function exportExcel({ statsData, cases, reportTitle, filename, generatedBy, chartEl }) {
  const wb = new ExcelJS.Workbook();
  wb.creator = generatedBy;

  // Summary sheet
  const ws = wb.addWorksheet('Summary');
  ws.getCell('A1').value = reportTitle;
  ws.getCell('A1').font = { bold: true, size: 14 };
  ws.getCell('A2').value = `Generated by ${generatedBy} on ${new Date().toLocaleDateString()}`;
  statsData.kpis.forEach((k, i) => {
    ws.getCell(`A${4 + i}`).value = k.label;
    ws.getCell(`A${4 + i}`).font = { bold: true };
    ws.getCell(`B${4 + i}`).value = k.value;
  });
  ws.getColumn(1).width = 28;
  ws.getColumn(2).width = 14;

  const img = await captureChart(chartEl);
  if (img) {
    const id = wb.addImage({ base64: img.dataUrl, extension: 'png' });
    const width = 720;
    ws.addImage(id, { tl: { col: 3, row: 3 }, ext: { width, height: (img.h / img.w) * width } });
  }

  // One sheet per table
  buildSections({ statsData, cases }).forEach((sec) => {
    const sheet = wb.addWorksheet(sec.title.slice(0, 31));
    const header = sheet.addRow(sec.headers);
    header.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    header.eachCell((c) => {
      c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFC00000' } };
    });
    sec.rows.forEach((r) => sheet.addRow(r));
    sheet.columns.forEach((col) => {
      const max = Math.max(...col.values.filter(Boolean).map((v) => String(v).length), 10);
      col.width = Math.min(max + 2, 40);
    });
  });

  const buf = await wb.xlsx.writeBuffer();
  saveAs(
    new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
    `${filename}.xlsx`
  );
}

// ── WORD ─────────────────────────────────────────────────────────────────────
const cell = (text, bold = false) =>
  new TableCell({
    children: [new Paragraph({ children: [new TextRun({ text: String(text ?? ''), bold, size: 18 })] })],
  });

const makeTable = (headers, rows) =>
  new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ tableHeader: true, children: headers.map((h) => cell(h, true)) }),
      ...rows.map((r) => new TableRow({ children: r.map((v) => cell(v)) })),
    ],
  });

export async function exportWord({ statsData, cases, reportTitle, filename, generatedBy, chartEl }) {
  const children = [
    new Paragraph({ text: reportTitle, heading: HeadingLevel.TITLE }),
    new Paragraph({ text: `Generated by ${generatedBy} on ${new Date().toLocaleDateString()}` }),
    new Paragraph({ text: 'Overview', heading: HeadingLevel.HEADING_2 }),
    makeTable(['Metric', 'Value'], statsData.kpis.map((k) => [k.label, k.value])),
  ];

  const img = await captureChart(chartEl);
  if (img) {
    const width = 600;
    children.push(
      new Paragraph({ text: 'Charts', heading: HeadingLevel.HEADING_2 }),
      new Paragraph({
        children: [
          new ImageRun({
            type: 'png',
            data: dataUrlToBytes(img.dataUrl),
            transformation: { width, height: Math.round((img.h / img.w) * width) },
          }),
        ],
      })
    );
  }

  buildSections({ statsData, cases }).forEach((sec) => {
    children.push(
      new Paragraph({ text: sec.title, heading: HeadingLevel.HEADING_2 }),
      makeTable(sec.headers, sec.rows)
    );
  });

  const doc = new Document({ sections: [{ children }] });
  saveAs(await Packer.toBlob(doc), `${filename}.docx`);
}